### ISSUE TITLE
Get Algorithm API Filter 문제

### ISSUE THREAD

**Issue by seungyong** [seungyong/algorithm#26]
### 현재 상황
1. rate, tag의 filter는 필수적이지 않은 parameter이지만, 400에러를 반환합니다.
2. sort가 정렬되지 않습니다.
3. 영어 대소문자를 구분합니다.

### 해결 방안
1. rate 값에 모두 ex) "a" 값을 추가하거나 또는 값을 보내지 않았을 떄는  정답률과 관계 없이 반환 합니다.
1-1. tag 값에 모두 ex) "1000" 값을 추가하거나 또는 값을 보내지 않았을 때는 알고리즘 분류와 관계 없이 반환합니다.
2. sort 정렬 추가
3. 영어 대소문자 구분 없애기

**Comment by seungyong** [comment]
1. 로그인이 되어있지 않은 상태에서는 sort가 정상적으로 작동하지만, 로그인이 되어있지 않다면 sort가 작동하지 않습니다.
2. 시도순이 제대로 작동하지 않습니다.

**Comment by dbstjdqls14** [comment]
백엔드 전체 리팩토링으로 인해 close합니다.

**Comment by dbstjdqls14** [comment]
백엔드 전체 리팩토링으로 인해 close합니다.
