### ISSUE TITLE
POST Code API 에러

### ISSUE THREAD

**Issue by seungyong** [seungyong/algorithm#27]
### 현재 상황
1. g++, gcc 설치가 안 되어 있어도 200이 반환됩니다.
2. 컴파일러 에러가 발생해도 200이 반환됩니다.
3. 코드를 통과해도 N차 통과, 실행시간을 알려주지 않습니다.
4. 정답을 맞추어도 정답을 맞춘 테이블에 아무것도 들어가 있지 않습니다.
5. 정답을 실패했든 성공했든 시도 횟수가 카운팅 되지 않습니다.
6. 코드 실행 시간은 해당 코드가 실행되는 순간에만 작동해야 합니다. 현재는 코드를 실행하고, 값을 비교하고 반환되는 값까지 실행 시간으로 치고 있습니다.
7. 실행 시간 초과 에러가 반환되지 않습니다.

### 해결 방안
1,2,3,7. response 변경
4,5. 테이블 로직 변경
6. 실행시간 타이머 위치 변경

**Comment by seungyong** [comment]
1. code 생성 object를 반환할 필요가 없습니다.
2. status created는 아무런 response를 가지지 않습니다. 200으로 변경 부탁드립니다.
3. 각 테스트케이스별 응답 값 변경이 필요합니다.
    3-1. 실행시간을 반환하지 않습니다.
    3-2. key 값이 한글입니다.
![image](https://github.com/seungyong/algorithm/assets/44765636/b6175ae9-ad93-473c-be35-2ce52617dfb5)

**Comment by dbstjdqls14** [comment]
백엔드 전체 리팩토링으로 인해 close합니다.
