### ISSUE TITLE
Algorithm Recommend API 문제

### ISSUE THREAD

**Issue by seungyong** [seungyong/algorithm#28]
### 현재 상황
1. tags가 없습니다.

### 해결 방안
1. tags 추가

**Comment by seungyong** [comment]
1. Get Algorithm Recommend API에 여전히 tags는 존재하지 않습니다. -> tags = kinds
2. Notion 상으로는 kind가 Array 형태일 때가 있는데 이또한 외래키로 인해서 하나의 알고리즘에 여러 개의 algorithm kinds가 들어갈 수 없습니다.

**Comment by dbstjdqls14** [comment]
백엔드 전체 리팩토링으로 인해 close합니다.
