### ISSUE TITLE
Post Board Image API 버그

### ISSUE THREAD

**Issue by seungyong** [seungyong/algorithm#30]
### 현재 상황
1. image를 넣으라면 /board/image/{boardId}가 필요한 상황인데 글을 작성할 때는 boardId를 가져올 수 없습니다.

### 해결 방안
1. board Image에서 boardID를 참조하는 것을 없애거나, 더미 이미지 테이블, 단순 이미지 저장소로 사용하는 등으로 boardId에 의존적이지 않아야 합니다.
1-1. 단, 쓰레기 데이터가 남았을 시 처리 방법을 생각해야 합니다.

**Comment by dbstjdqls14** [comment]
백엔드 전체 리팩토링으로 인해 close합니다.
