### ISSUE TITLE
Get Board API 버그

### ISSUE THREAD

**Issue by seungyong** [seungyong/algorithm#33]
### 현재 상황
1. 최신순이 아닌 오래된 순으로 가져옵니다.
2. 피드백을 하면 질문 게시글이 반환됩니다.
![image](https://github.com/seungyong/algorithm/assets/44765636/a4e95e93-aa69-42bf-87b5-4846375a3e78)

### 해결 방안
1. 최신순으로 가져오기
2. 피드백으로 반환

**Comment by seungyong** [comment]
1. GET /board/algorithm/{algorithm_id} API에서 total 값이 알고리즘 게시판의 총 개수가 아닌 반환 개수를 반환합니다.
![image](https://github.com/seungyong/algorithm/assets/44765636/e830b587-6eb2-4e85-a6fa-06b7ab5e5008)

**Comment by dbstjdqls14** [comment]
백엔드 전체 리팩토링으로 인해 close합니다.
