### ISSUE TITLE
POST /board 버그

### ISSUE THREAD

**Issue by seungyong** [seungyong/algorithm#38]
### 현재 상황
1. Notion 상에는 algorithm_id를 추가하지 않으면 일반 게시판으로 분류된다고 되어있는데, algorithm_id가 없으면 Bad Request 에러를 반환합니다.
1-1. 피드백만 제외되어 있습니다.

### 해결 방안
1. 일반 질문도 algorithm_id를 안 보낼 수 있도록 변경

**Comment by dbstjdqls14** [comment]
백엔드 전체 리팩토링으로 인해 close합니다.
