### ISSUE TITLE
Recommend API 설계 문제

### ISSUE THREAD

**Issue by seungyong** [seungyong/algorithm#43]
### 현재 상황
1. 추천을 하기 위해서는 path parameter에 value라는 값을 사용합니다.
POST인데 body가 아닌 path parameter를 사용하는 이유가 궁금합니다.
2. value의 범위 문제

### 해결 방안
1. board, comment, code는 각각의 recommend POST 메소드 1개를 가지게 하고, body로 boolean value를 받습니다.
2. 각 recommend 테이블은 value를 -1, 0, 1로 제한합니다.
    2-1. 현재 value는 big int로 되어 있습니다. (저장공간 낭비) -> tinyint(3)

**Comment by dbstjdqls14** [comment]
백엔드 전체 리팩토링으로 인해 close합니다.
